# Generated by Django 3.0 on 2025-10-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(help_text='Insira a data no formato dd-mm-aaaa', verbose_name='Data de Nascimento')),
                ('numero_casa', models.CharField(max_length=3, verbose_name='Número da casa')),
                ('placa_do_veiculo', models.CharField(max_length=7, verbose_name='Placa do veículo')),
                ('horario_de_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Horário de entrada')),
                ('horario_de_saida', models.DateTimeField(verbose_name='Horário de saída')),
                ('horario_de_autorizacao_entrada', models.DateTimeField(auto_now=True, verbose_name='Horário de entrada autorizada')),
                ('nome_do_morador', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('porteiro_que_autorizou_entrada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='porteiros.Porteiro', verbose_name='Porteiro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
