# Generated by Django 3.0 on 2025-10-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='horario_de_entrada',
            field=models.DateTimeField(verbose_name='Horário de entrada'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='placa_do_veiculo',
            field=models.CharField(max_length=8, verbose_name='Placa do veículo'),
        ),
    ]
